package ua.ek.utils;

public enum PageType {
    HOME_PAGE,
    REGISTRATION_PAGE,
    AUTH_PAGE,
    USER_PROFILE_PAGE,
    TABLET_PAGE,
    TABLETS_PAGE,
    TABLETS_LIST_PAGE,
    TABLETS_MANUFACTURER_PAGE,
    APPLE_TABLETS_PAGE,
    SEARCH_PAGE,
    SEARCH_RESULT_PAGE,
    PRICE_FILTER_PAGE;
}
