package ua.ek.utils;

public enum StepType {
    HOME_STEP,
    REGISTRATION_STEP,
    AUTH_STEP,
    USER_PROFILE_STEP,
    TABLET_STEP,
    TABLETS_STEP,
    TABLETS_LIST_STEP,
    TABLETS_MANUFACTURER_STEP,
    APPLE_TABLETS_STEP,
    SEARCH_STEP,
    PRICE_FILTER_STEP;
}